entity/OrderExtendedEntities.xml
service/oms.rest.xml

…ned GET order and POST order rest endpoints.

Extended OrderHeader entity to define relationships and masters. Defined GET order and POST order rest endpoints.

---

entity/OmsExtendedEntities.xml
entity/OrderExtendedEntities.xml
entity/PartyExtendedEntities.xml
entity/ProductExtendedEntities.xml

1. Fixed xsd location in entity files from 2.1 to 3

Fixed: xsd location in the entities file

---

service/co/hotwax/oms/product/ProductServices.xml

1. Fixed entity name for Product Feature.
2. Moved the ProductServices under Product directory.

Fixed: entity name for productFeature and moved ProductServices in Product directory

---

service/co/hotwax/oms/product/ProductServices.xml

1. Added a new service to create virtual products that will create the product record and shopify shop product record.
2. Added transaction=force-new for create#ProductVariant service call

Handle creating products without internalName

---

service/co/hotwax/oms/product/ProductServices.xml

Fixed: typo while updating Product

Fixed: typo while updating product

---

service/co/hotwax/oms/product/ProductServices.xml

1. Check if the product already exists while creating and updating product if yes then set the productId.

Improved: Product Create and Update services to check if the Product exists

---

data/UpgradeData_V1.0.0.xml

1. Added upgrade data files and updated the receivePath and receiveMovePath in CreateProductsFeed and UpdateProductsFeed.

Added upgrade Data file 

---

service/oms.rest.xml

Done following-
1) Changed Get Product Stores API to return data from ProductStore entity only.
2) Added a separate endpoint to get shipment method counts for the product stores.

Improved: Changed Get Product Stores API to return data from ProductStore entity (#67).

---

service/co/hotwax/oms/common/CommonServices.xml

Cherry picked the check parent type service to hotfix on v1.0.5 branch.

Cherry picked the check parent type service to hotfix on v1.0.5 branch

---

service/co/hotwax/oms/impl/OrderReservationServices.xml
service/co/hotwax/oms/search/SearchServices.xml
service/oms.secas.xml

- Added seca rule to index order reservation document
- Added service to call oms create oisgir index service, these should be call using data feed, will update code later to use DataFeed.
- Fixed inventory reservation servie to not try the inventory reservation if item moved to virtual facility

Worked on following:

---

entity/ProductExtendedEntities.xml

1. Added Product Attributes relation in Product.

Added: Product Attribute relation in product

---

data/SeedData.xml
data/UpgradeData_v1.0.3.xml
data/UpgradeData_v1.0.6.xml

1. Added enumeration data for product keyword type.

Added enumeration data for product type keyword

---

data/SeedData.xml
data/UpgradeData_v1.0.3.xml
data/UpgradeData_v1.0.6.xml

1. Backported enumeration data for product type keyword to v1.1.1

Backport enumeration data for product type keyword to v1.1.1

---

upgrade/upcoming/UpgradeSQL.sql

Added upgrade SQL for removing service job and related data

Added: upgrade SQL for removing service job and related records for obsolete product sync jobs

---

entity/OmsViewEntities.xml
service/co/hotwax/oms/order/TransferOrderServices.xml
service/oms.rest.xml

API to get Transfer Orders

---

service/co/hotwax/orderledger/order/TransferOrderServices.xml
service/oms.rest.xml

Closes: #159  
Changelog: Added

Added: API to get transfer order details

---

data/ServiceJobData.xml
data/UpgradeData_Upcoming.xml
service/co/hotwax/orderledger/order/TransferOrderServices.xml

1. Added service for bulk approve Store Fulfill Transfer Orders.
2. Added service job and enum data for bulk approve Store Fulfill Transfer Orders.
3. Added service for approve Store Fulfill Transfer Order.
Closes #165

Added: Approve Store Fulfill Transfer Orders

---

data/OmsEnumData.xml
data/ServiceJobData.xml
data/UpgradeData_Upcoming.xml
service/co/hotwax/oms/order/TransferOrderServices.xml
service/co/hotwax/orderledger/order/TransferOrderServices.xml

1. Added service for bulk approve Wh Fulfill Transfer Orders.
2. Added service job and enum data for bulk approve Wh Fulfill Transfer Orders.
3. Added service for approve Wh Fulfill Transfer Order.
Closes #87

Added: Approve Warehouse Fulfill Transfer Orders

---

service/co/hotwax/oms/order/OrderServices.xml

Fixed rejectOrderItems service to reject related order items with appropriate reasons instead of same as main item rejection reason

---

service/co/hotwax/orderledger/order/test-scripts/CreateTestTransferOrderServices.xml

1. to create quantity greater than 0 and 
2. not include _NA_ productId

Improved test service to generate wh to store TOs

---

service/co/hotwax/orderledger/order/TransferOrderServices.xml

Fixed the possible error for user to be logged in for service job scheduling of approve TO Service Jobs

Added the authenticate anonymous-all attribute for Bulk Approve TO Jobs

---

service/co/hotwax/orderledger/order/test-scripts/CreateTestTransferOrderServices.xml

Added: Test Services to generate sample STW and STS transfer orders

---

data/ServiceJobData.xml

- Updated the `ServiceJob` entity data with `instanceOfProductId` field populated.
- The new version of job manager app will work on `ServiceJobAndProduct` model instead of `ServiceJobAndEnum` model.

Updated the ServiceJob entity data

---

service/oms.rest.xml

1. Added API endpoints for Create#ProductVariant and update#ProductVariant.

Added API endpoints for create#ProductVariant and update#ProductVariant services

---

service/co/hotwax/oms/order/OrderServices.xml

Improved: Used reasonEnumId to create InventoryItemVariance in reject#OrderItem service

---

service/oms.rest.xml

Added: API end-points to Create TO and Approve Store Fulfill Transfer Order

---

service/oms.rest.xml

Improved: Added API to create communication event(#209).

Improved: Added API to create communication event(#209).

---

entity/OmsViewEntities.xml

Related Issue: https://git.hotwax.co/commerce/poorti/-/issues/82

Added view entity to link user login with security permission

---

entity/OmsExtendedEntities.xml
service/oms.rest.xml

Improved: Added master-detail relationship to fetch shipment box type detail while fetching carrier shipment box types (#217)

Improved: Added master-detail relationship to fetch shipment box type detail while fetching carrier shipment box types (#217)

---

service/co/hotwax/orderledger/order/TransferOrderServices.xml

Revert "Fixed: Rejected TO should not be visible in the Receiving App"

---

entity/OmsViewEntities.xml

1. Added a view entity, TransferOrderAndItem to get the transfer order item and details.

Added: View entity to get transfer order and item details

---

service/co/hotwax/orderledger/order/TransferOrderServices.xml
service/oms.rest.xml

1. Added an api to get transfer orders based on grouping, filters and sorting.
2. Added an api to get the item details for the given conditions.

Added: Service and api to get the transfer order items and details.

---

service/oms.rest.xml

1. Added api to fetch order status for an orderId.

Added: API to fetch Order status for an order Id

---

service/co/hotwax/orderledger/order/TransferOrderServices.xml

1. Added currencyUom,shipmentMethodTypeId,carrierPartyId,facilityId and orderFacilityId at header level and the unitPrice at item level in the get#TransferOrder service.

Improved: Get Transfer order api for TO app

---

service/co/hotwax/orderledger/product/ProductServices.xml

Added: Service to store Product Average Cost

---

service/co/hotwax/orderledger/order/OrderServices.xml

Added: date-filter in PicklistShipmentAndRole entity wherever being used in services

---

entity/OmsViewEntities.xml
service/co/hotwax/orderledger/order/email/EmailServices.xml

closes: [#13](https://git.hotwax.co/sm/stevemadden/-/issues/13)
This PR includes various fixes related to bopis emails and reminder emails service.

Added the pickup reminder email service and bopis email fixes
